/* AUTO-GENERATED by scripts/collect-licenses.mjs - 请勿手改
   本项目的开源依赖清单（按用途分类，样式对齐酷安《开源相关》）。 */

export interface LicenseEntry {
  title: string;
  version: string;
  license: string;
  holder: string;
  url: string;
  note?: string;
  category?: string;
}

export interface LicenseGroup {
  id: string;
  title: string;
  note: string;
  items: LicenseEntry[];
}

export const LICENSE_GROUPS: LicenseGroup[] = [
  {
    "id": "ui",
    "title": "界面与组件",
    "note": "界面框架与 Material 3 组件",
    "items": [
      {
        "category": "ui",
        "title": "@material/web",
        "version": "2.5.0",
        "license": "Apache-2.0",
        "holder": "未提供版权方信息",
        "url": "https://github.com/material-components/material-web"
      },
      {
        "category": "ui",
        "title": "react",
        "version": "19.3.0",
        "license": "MIT",
        "holder": "未提供版权方信息",
        "url": "https://react.dev/"
      },
      {
        "category": "ui",
        "title": "react-dom",
        "version": "19.3.0",
        "license": "MIT",
        "holder": "未提供版权方信息",
        "url": "https://react.dev/"
      }
    ]
  },
  {
    "id": "design",
    "title": "设计系统 · 图标 · 字体",
    "note": "配色算法、图标字体与字体裁剪",
    "items": [
      {
        "category": "design",
        "title": "@fontsource/roboto",
        "version": "5.3.0",
        "license": "OFL-1.1",
        "holder": "Google Inc.",
        "url": "https://fontsource.org/fonts/roboto"
      },
      {
        "category": "design",
        "title": "@material/material-color-utilities",
        "version": "0.4.0",
        "license": "Apache-2.0",
        "holder": "Material Eng",
        "url": "https://github.com/material-foundation/material-color-utilities/tree/main/typescript"
      },
      {
        "category": "design",
        "title": "fontkit",
        "version": "2.0.4",
        "license": "MIT",
        "holder": "Devon Govett",
        "url": "https://www.npmjs.com/package/fontkit"
      },
      {
        "category": "design",
        "title": "material-symbols",
        "version": "0.47.4",
        "license": "Apache-2.0",
        "holder": "未提供版权方信息",
        "url": "https://marella.github.io/material-symbols/demo/"
      },
      {
        "category": "design",
        "title": "Roboto",
        "version": "variable",
        "license": "Apache License 2.0",
        "holder": "Google Fonts",
        "url": "https://fonts.google.com/specimen/Roboto"
      },
      {
        "category": "design",
        "title": "subset-font",
        "version": "2.7.0",
        "license": "BSD-3-Clause",
        "holder": "Andreas Lind",
        "url": "https://github.com/papandreou/subset-font"
      }
    ]
  },
  {
    "id": "build",
    "title": "构建与开发工具",
    "note": "打包、类型与样式处理",
    "items": [
      {
        "category": "build",
        "title": "@vitejs/plugin-react",
        "version": "5.2.0",
        "license": "MIT",
        "holder": "Evan You",
        "url": "https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react"
      },
      {
        "category": "build",
        "title": "typescript",
        "version": "5.9.3",
        "license": "Apache-2.0",
        "holder": "Microsoft Corp.",
        "url": "https://www.typescriptlang.org/"
      },
      {
        "category": "build",
        "title": "vite",
        "version": "7.3.6",
        "license": "MIT",
        "holder": "Evan You",
        "url": "https://vite.dev"
      }
    ]
  },
  {
    "id": "test",
    "title": "测试与验证",
    "note": "自动化验收与逐屏视觉校验",
    "items": [
      {
        "category": "test",
        "title": "playwright",
        "version": "1.63.0",
        "license": "Apache-2.0",
        "holder": "Microsoft Corporation",
        "url": "https://playwright.dev"
      }
    ]
  },
  {
    "id": "android",
    "title": "Android 运行时",
    "note": "APK（WebView 宿主）用到的库",
    "items": [
      {
        "category": "android",
        "title": "androidx.activity:activity-ktx",
        "version": "1.10.0",
        "license": "Apache License 2.0",
        "holder": "The Android Open Source Project",
        "url": "https://developer.android.com/jetpack/androidx/releases/activity"
      },
      {
        "category": "android",
        "title": "androidx.core:core-ktx",
        "version": "1.15.0",
        "license": "Apache License 2.0",
        "holder": "The Android Open Source Project",
        "url": "https://developer.android.com/jetpack/androidx"
      },
      {
        "category": "android",
        "title": "androidx.webkit:webkit",
        "version": "1.12.1",
        "license": "Apache License 2.0",
        "holder": "The Android Open Source Project",
        "url": "https://developer.android.com/jetpack/androidx/releases/webkit"
      },
      {
        "category": "android",
        "title": "Kotlin Standard Library",
        "version": "2.0.x",
        "license": "Apache License 2.0",
        "holder": "JetBrains",
        "url": "https://kotlinlang.org"
      }
    ]
  },
  {
    "id": "infra",
    "title": "部署与安全",
    "note": "反爬、CDN 与持续监控",
    "items": [
      {
        "category": "infra",
        "title": "Anubis",
        "version": "v1.27.0（deploy/anubis 锁定）",
        "license": "MIT License",
        "holder": "TecharoHQ",
        "url": "https://github.com/TecharoHQ/anubis",
        "note": "反爬防火墙：配置文件与监控工作流在 deploy/anubis/"
      },
      {
        "category": "infra",
        "title": "Cloudflare CDN / Pages",
        "version": "—",
        "license": "商业服务（配置见 deploy/cloudflare）",
        "holder": "Cloudflare, Inc.",
        "url": "https://www.cloudflare.com",
        "note": "可选的边缘缓存与 Pages 托管说明"
      }
    ]
  },
  {
    "id": "other",
    "title": "其他",
    "note": "未归类的依赖",
    "items": [
      {
        "category": "other",
        "title": "@techstark/opencv-js",
        "version": "5.0.0-release.1",
        "license": "Apache-2.0",
        "holder": "Wilson",
        "url": "https://github.com/TechStark/opencv-js"
      },
      {
        "category": "other",
        "title": "@types/react",
        "version": "19.3.0",
        "license": "MIT",
        "holder": "Asana",
        "url": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react"
      },
      {
        "category": "other",
        "title": "@types/react-dom",
        "version": "19.3.0",
        "license": "MIT",
        "holder": "Asana",
        "url": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom"
      },
      {
        "category": "other",
        "title": "tesseract.js",
        "version": "7.0.0",
        "license": "Apache-2.0",
        "holder": "未提供版权方信息",
        "url": "https://github.com/naptha/tesseract.js"
      }
    ]
  }
];

/** 仅作参考、未引入代码的第三方实现 */
export const REFERENCE_LIBS: LicenseEntry[] = [
  {
    "title": "AndroidLiquidGlass",
    "version": "—",
    "license": "Apache License 2.0",
    "holder": "Kyant0",
    "url": "https://github.com/Kyant0/AndroidLiquidGlass",
    "note": "酷安底边栏液体玻璃的实现（本项目仅参考其思路：背景采样 + 色调 + 边缘渐隐 + 触摸光斑）"
  },
  {
    "title": "Shapes",
    "version": "—",
    "license": "Apache License 2.0",
    "holder": "Kyant",
    "url": "https://github.com/Kyant0/AndroidLiquidGlass",
    "note": "酷安使用的形状库（胶囊/圆角）"
  },
  {
    "title": "free_reflection",
    "version": "2.0.0",
    "license": "未提供许可信息",
    "holder": "weishu",
    "url": "https://github.com/tiann/FreeReflection",
    "note": "酷安用于反射调用隐藏 API"
  },
  {
    "title": "liquid-glass-react",
    "version": "1.1.1",
    "license": "MIT License",
    "holder": "rdev",
    "url": "https://github.com/rdev/liquid-glass-react",
    "note": "Apple 风格 Liquid Glass 的 React 实现（已装依赖，当前底边栏为自绘）"
  },
  {
    "title": "liquid-dom",
    "version": "—",
    "license": "MIT License",
    "holder": "Andrew Prifer",
    "url": "https://github.com/AndrewPrifer/liquid-dom",
    "note": "Web 端玻璃透镜折射参考"
  },
  {
    "title": "shuding/liquid-glass",
    "version": "—",
    "license": "MIT License",
    "holder": "Shu Ding",
    "url": "https://github.com/shuding/liquid-glass",
    "note": "SVG + Canvas 玻璃着色器参考"
  }
];
